# Generated by Django 5.1.4 on 2025-01-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category"],
                "permissions": [
                    ("can_edit_name", "can edit name"),
                    ("can_edit_descriptions", "can edit descriptions"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="view_counter",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
