# Generated by Django 5.1.4 on 2025-02-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_options_product_view_counter"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="flag_public",
            field=models.BooleanField(default=False),
        ),
    ]
